spring.datasource.url=jdbc:postgresql://${{Postgres.PGHOST}}:${{Postgres.PGPORT}}/${{Postgres.PGDATABASE}}
spring.datasource.username=${{Postgres.PGUSER}}
spring.datasource.password=${{Postgres.PGPASSWORD}}
spring.jpa.hibernate.ddl-auto=update
